name: 'snowplow_web'
version: '0.1.0'
config-version: 2

require-dbt-version: ">=0.18.0" # TODO:Check this

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]


target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  # Sources
  # snowplow__atomic_schema: Only set if not using 'atomic' schema for Snowplow events data
  # snowplow__database: Only set if not using target.database for Snowplow events data
  snowplow__events: "{{ source('atomic','events') }}"
  snowplow__page_view_context: "{{ source('atomic','com_snowplowanalytics_snowplow_web_page_1') }}"
  snowplow__iab_context: "{{ source('atomic','com_iab_snowplow_spiders_and_robots_1') }}"
  snowplow__ua_parser_context: "{{ source('atomic','com_snowplowanalytics_snowplow_ua_parser_context_1') }}"
  snowplow__yauaa_context: "{{ source('atomic','nl_basjes_yauaa_context_1') }}"
  snowplow__sessions_table: "{{ ref('snowplow_web_sessions') }}" # Change to your custom sessions table if you have disabled the standard sessions table in favour of a custom version. Advanced config.
  # Variables
  snowplow__start_date: '2020-01-01'
  snowplow__lookback_window_hours: 6
  snowplow__backfill_limit_days: 30
  snowplow__session_lookback_days: 365
  snowplow__days_late_allowed: 3
  snowplow__min_visit_length: 5
  snowplow__heartbeat: 10
  snowplow__upsert_lookback_days: 30
  snowplow__app_id: []
  snowplow__enable_iab: false
  snowplow__enable_ua: false
  snowplow__enable_yauaa: false
  snowplow__ua_bot_filter: true
  # can probably remove these flags by setting to disabled under models:
  snowplow__enable_derived_page_views: true
  snowplow__enable_derived_sessions: true
  snowplow__enable_derived_users: true



# on-run-start: "{{ snowplow_utils.snowplow_incremental_pre_hook('snowplow_web') }}"
# Teardown all web manifest tables if true.
on-run-start: "{{ snowplow_utils.snowplow_teardown_all('snowplow_web', var('snowplow_web_teardown_all', false)) }}"

# Update manifest table with last event consumed per sucessfully executed node/model
on-run-end: "{{ snowplow_utils.snowplow_incremental_post_hook('snowplow_web') }}"


# Tag 'snowplow_web_incremental' allows snowplow_incremental_post_hook to identify Snowplow models
# and add their last sucessfull collector_tstamp to the manifest.
models:
  snowplow_web:
    base:
      +schema: derived 
      scratch:
        +schema: scratch
        redshift:
          enabled: "{{ target.type == 'redshift' | as_bool() }}"
    page_views:
      +tags: snowplow_web_incremental
      +schema: derived
      scratch:
        +schema: scratch
        redshift:
          enabled: "{{ target.type == 'redshift' | as_bool() }}"
    sessions:
      +tags: snowplow_web_incremental
      +schema: derived
      scratch:
        +schema: scratch
    users:
      +tags: snowplow_web_incremental
      +schema: derived
      scratch:
        +schema: scratch
    custom_example:
      +tags: snowplow_web_incremental
      +schema: derived
