version: 2

models:
  - name: snowplow_web_base_sessions_lifecycle
    description: '{{ doc("table_base_sessions_lifecycle") }}'
    columns:
      - name: session_id
        description: A UUID generated for each session
      - name: start_tstamp
        description: The `collector_tstamp` when the session began
      - name: end_tstamp
        description: The `collector_tstamp` when the session ended
  - name: snowplow_web_current_incremental_tstamp
    description: '{{ doc("table_current_incremental_tstamp") }}'
    columns:
      - name: lower_limit
        description: The lower `collector_tstamp` limit for the run
      - name: upper_limit
        description: The upper `collector_tstamp` limit for the run
  - name: snowplow_web_base_events_this_run
    description: '{{ doc("table_base_events_this_run") }}'
    columns:
      - name: app_id
        description: Application ID e.g. ‘angry-birds’ is used to distinguish different applications that are being tracked by the same Snowplow stack, e.g. production versus dev.
      - name: platform
        description: Platform e.g. ‘web’
      - name: etl_tstamp
        description: Timestamp event began ETL e.g. ‘2017-01-26 00:01:25.292’
      - name: collector_tstamp
        description: Time stamp for the event recorded by the collector e.g. ‘2013-11-26 00:02:05’
      - name: dvce_created_tstamp
        description: Timestamp event was recorded on the client device e.g. ‘2013-11-26 00:03:57.885’
      - name: event
        description: The type of event recorded e.g. ‘page_view’
      - name: event_id
        description: A UUID for each event e.g. ‘c6ef3124-b53a-4b13-a233-0088f79dcbcb’
        tags:
          - primary-key
        tests:
          - unique
          - not_null
      - name: txn_id
        description: Transaction ID set client-side, used to de-dupe records e.g. 421828
      - name: name_tracker
        description: Tracker namespace e.g. ‘sp1’
      - name: v_tracker
        description: Tracker version e.g. ‘js-3.0.0’
      - name: v_collector
        description: Collector version e.g. ‘ssc-2.1.0-kinesis’
      - name: v_etl
        description: ETL version e.g. ‘snowplow-micro-1.1.0-common-1.4.2’
      - name: user_id
        description: Unique ID set by business e.g. ‘jon.doe@email.com’
      - name: user_ipaddress
        description: User IP address e.g. ‘92.231.54.234’
      - name: user_fingerprint
        description: A user fingerprint generated by looking at the individual browser features e.g. 2161814971
      - name: domain_userid
        description: User ID set by Snowplow using 1st party cookie e.g. ‘bc2e92ec6c204a14’
      - name: domain_sessionidx
        description: A visit / session index e.g. 3
      - name: network_userid
        description: User ID set by Snowplow using 3rd party cookie e.g. ‘ecdff4d0-9175-40ac-a8bb-325c49733607’
      - name: geo_country
        description: ISO 3166-1 code for the country the visitor is located in e.g. ‘GB’, ‘US’
      - name: geo_region
        description: ISO-3166-2 code for country region the visitor is in e.g. ‘I9’, ‘TX’
      - name: geo_city
        description: City the visitor is in e.g. ‘New York’, ‘London’
      - name: geo_zipcode
        description: Postcode the visitor is in e.g. ‘94109’
      - name: geo_latitude
        description: Visitor location latitude e.g. 37.443604
      - name: geo_longitude
        description: Visitor location longitude e.g. -122.4124
      - name: geo_region_name
        description: Visitor region name e.g. ‘Florida’
      - name: ip_isp
        description: Visitor’s ISP e.g. ‘FDN Communications’
      - name: ip_organization
        description: Organization associated with the visitor’s IP address – defaults to ISP name if none is found e.g. ‘Bouygues Telecom’
      - name: ip_domain
        description: Second level domain name associated with the visitor’s IP address e.g. ‘nuvox.net’
      - name: ip_netspeed
        description: Visitor’s connection type e.g. ‘Cable/DSL’
      - name: page_url
        description: The page URL e.g. ‘http://www.example.com’
      - name: page_title
        description: Web page title e.g. ‘Snowplow Docs – Understanding the structure of Snowplow data’
      - name: page_referrer
        description: URL of the referrer e.g. ‘http://www.referrer.com’
      - name: page_urlscheme
        description: Scheme aka protocol e.g. ‘https’
      - name: page_urlhost
        description: Host aka domain e.g. ‘“www.snowplowanalytics.com’
      - name: page_urlport
        description: Port if specified, 80 if not 80
      - name: page_urlpath
        description: Path to page e.g. ‘/product/index.html’
      - name: page_urlquery
        description: Querystring e.g. ‘id=GTM-DLRG’
      - name: page_urlfragment
        description: Fragment aka anchor e.g. ‘4-conclusion’
      - name: refr_urlscheme
        description: Referer scheme e.g. ‘http’
      - name: refr_urlhost
        description: Referer host e.g. ‘www.bing.com’
      - name: refr_urlport
        description: Referer port e.g. 80
      - name: refr_urlpath
        description: Referer page path e.g. ‘/images/search’
      - name: refr_urlquery
        description: Referer URL querystring e.g. ‘q=psychic+oracle+cards’
      - name: refr_urlfragment
        description: Referer URL fragment
      - name: refr_medium
        description: Type of referer e.g. ‘search’, ‘internal’
      - name: refr_source
        description: Name of referer if recognised e.g. ‘Bing images’
      - name: refr_term
        description: Keywords if source is a search engine e.g. ‘psychic oracle cards’
      - name: mkt_medium
        description: Type of traffic source e.g. ‘cpc’, ‘affiliate’, ‘organic’, ‘social’
      - name: mkt_source
        description: The company / website where the traffic came from e.g. ‘Google’, ‘Facebook’
      - name: mkt_term
        description: Any keywords associated with the referrer e.g. ‘new age tarot decks’
      - name: mkt_content
        description: The content of the ad. (Or an ID so that it can be looked up.) e.g. 13894723
      - name: mkt_campaign
        description: The campaign ID e.g. ‘diageo-123’
      - name: se_category
        description: Category of event e.g. ‘ecomm’, ‘video’
      - name: se_action
        description: Action performed / event name e.g. ‘add-to-basket’, ‘play-video’
      - name: se_label
        description: The object of the action e.g. the ID of the video played or SKU of the product added-to-basket e.g. ‘pbz00123’
      - name: se_property
        description: A property associated with the object of the action e.g. ‘HD’, ‘large’
      - name: se_value
        description: A value associated with the event / action e.g. the value of goods added-to-basket e.g. 9.99
      - name: tr_orderid
        description: Order ID e.g. ‘#134’
      - name: tr_affiliation
        description: Transaction affiliation (e.g. store where sale took place) e.g. ‘web’
      - name: tr_total
        description: Total transaction value e.g. 12.99
      - name: tr_tax
        description: Total tax included in transaction value e.g. 3.00
      - name: tr_shipping
        description: Delivery cost charged e.g. 0.00
      - name: tr_city
        description: Delivery address, city e.g. ‘London’
      - name: tr_state
        description: Delivery address, state e.g. ‘Washington’
      - name: tr_country
        description: Delivery address, country e.g. ‘France’
      - name: ti_orderid
        description: Order ID e.g. ‘#134’
      - name: ti_sku
        description: Product SKU e.g. ‘pbz00123’
      - name: ti_name
        description: Product name e.g. ‘Cone pendulum’
      - name: ti_category
        description: Product category e.g. ‘New Age’
      - name: ti_price
        description: Product unit price e.g. 9.99
      - name: ti_quantity
        description: Number of product in transaction e.g. 2
      - name: pp_xoffset_min
        description: Minimum page x offset seen in the last ping period e.g. 0
      - name: pp_xoffset_max
        description: Maximum page x offset seen in the last ping period e.g. 100
      - name: pp_yoffset_min
        description: Minimum page y offset seen in the last ping period e.g. 0
      - name: pp_yoffset_max
        description: Maximum page y offset seen in the last ping period e.g. 200
      - name: useragent
        description: Raw useragent
      - name: br_name
        description: Browser name e.g. ‘Firefox 12’
      - name: br_family
        description: Browser family e.g. ‘Firefox’
      - name: br_version
        description: Browser version e.g. ‘12.0’
      - name: br_type
        description: Browser type e.g. ‘Browser’
      - name: br_renderengine
        description: Browser rendering engine e.g. ‘GECKO’
      - name: br_lang
        description: Language the browser is set to e.g. ‘en-GB’
      - name: br_features_pdf
        description: Whether the browser recognizes PDFs e.g. True
      - name: br_features_flash
        description: Whether Flash is installed e.g. True
      - name: br_features_java
        description: Whether Java is installed e.g. True
      - name: br_features_director
        description: Whether Adobe Shockwave is installed e.g. True
      - name: br_features_quicktime
        description: Whether QuickTime is installed e.g. True
      - name: br_features_realplayer
        description: Whether RealPlayer is installed e.g. True
      - name: br_features_windowsmedia
        description: Whether mplayer2 is installed e.g. True
      - name: br_features_gears
        description: Whether Google Gears is installed e.g. True
      - name: br_features_silverlight
        description: Whether Microsoft Silverlight is installed e.g. True
      - name: br_cookies
        description: Whether cookies are enabled e.g. True
      - name: br_colordepth
        description: Bit depth of the browser color palette e.g. 24
      - name: br_viewwidth
        description: Viewport width e.g. 1000
      - name: br_viewheight
        description: Viewport height e.g. 1000
      - name: os_name
        description: Name of operating system e.g. ‘Android’
      - name: os_family
        description: Operating system family e.g. ‘Linux’
      - name: os_manufacturer
        description: Company responsible for OS e.g. ‘Apple’
      - name: os_timezone
        description: Client operating system timezone e.g. ‘Europe/London’
      - name: dvce_type
        description: Type of device e.g. ‘Computer’
      - name: dvce_ismobile
        description: Is the device mobile? e.g. True
      - name: dvce_screenwidth
        description: Screen width in pixels e.g. 1900
      - name: dvce_screenheight
        description: Screen height in pixels e.g. 1024
      - name: doc_charset
        description: The page’s character encoding e.g. , ‘UTF-8’
      - name: doc_width
        description: The page’s width in pixels e.g. 1024
      - name: doc_height
        description: The page’s height in pixels e.g. 3000
      - name: tr_currency
        description: Currency e.g. ‘USD’
      - name: tr_total_base
        description: Total in base currency e.g. 12.99
      - name: tr_tax_base
        description: Total tax in base currency e.g. 3.00
      - name: tr_shipping_base
        description: decimal  Delivery cost in base currency e.g. 0.00
      - name: ti_currency
        description: Currency e.g. ‘EUR’
      - name: ti_price_base
        description: decimal Price in base currency e.g. 9.99
      - name: base_currency
        description: Reporting currency e.g. ‘GBP’
      - name: geo_timezone
        description: Visitor timezone name e.g. ‘Europe/London’
      - name: mkt_clickid
        description: The click ID e.g. ‘ac3d8e459’
      - name: mkt_network
        description: The ad network to which the click ID belongs e.g. ‘DoubleClick’
      - name: etl_tags
        description: JSON of tags for this ETL run e.g. “[‘prod’]”
      - name: dvce_sent_tstamp
        description: When the event was sent by the client device e.g. ‘2013-11-26 00:03:58.032’
      - name: refr_domain_userid
        description: The Snowplow domain_userid of the referring website e.g. ‘bc2e92ec6c204a14’
      - name: refr_dvce_tstamp
        description: The time of attaching the domain_userid to the inbound link e.g. ‘2013-11-26 00:02:05’
      - name: domain_sessionid
        description: A visit / session identifier e.g. ‘c6ef3124-b53a-4b13-a233-0088f79dcbcb’
      - name: derived_tstamp
        description: Timestamp making allowance for innaccurate device clock e.g. ‘2013-11-26 00:02:04’
      - name: event_vendor
        description: Who defined the event e.g. ‘com.acme’
      - name: event_name
        description: Event name e.g. ‘link_click’
      - name: event_format
        description: Format for event e.g. ‘jsonschema’
      - name: event_version
        description: Version of event schema e.g. ‘1-0-2’
      - name: event_fingerprint
        description: Hash client-set event fields e.g. AADCE520E20C2899F4CED228A79A3083
      - name: true_tstamp
        description: User-set “true timestamp” for the event e.g. ‘2013-11-26 00:02:04’
      - name: page_view_id
        description: An identifier for each page view. This is provided by the page view context.
